version: "2"
   
services:
  juego_nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment: 
      - PUBLIC_JWT=publica.key
      - VERIFICAR_JWT=true
      - urlUsarios=http://18.191.208.8:3050
      - urlDados=http://35.225.47.35:5002
      - urlTorneo=http://13.67.221.132:5000
      - urlToken=http://35.232.54.106:80
      - TOKEN_ID=juegos5
      - TOKEN_SECRET=juegos5-567
    command: npm start
  sonarqube:
    container_name:  sonarqube
    image:  sonarqube:latest
    ports:
        -  "9000:9000"
        -  "9092:9092"

