version: "2"
   
services:
  juego_nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment: 
      - PUBLIC_JWT=AQUIDEBEIRLALLAVEPUBLICA
      - urlUsarios=http://104.155.167.93:800
      - urlDados=http://104.155.167.93:8001
      - urlTorneo=http://104.155.167.93:8002
    command: npm start

