version: "2"
   
services:
  juego_nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment: 
      - PUBLIC_JWT=AQUIDEBEIRLALLAVEPUBLICA
    command: npm start

