version: "2"
   
services:
  juego_nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment: 
      - PUBLIC_JWT=oauth-public.key
      - VERIFICAR_JWT=true
      - urlUsarios=http://104.155.167.93:8000
      - urlDados=http://104.155.167.93:8001
      - urlTorneo=http://104.155.167.93:8002
      - urlToken=http://35.202.77.9/api/token
      - TOKEN_ID=1
      - TOKEN_SECRET=2xsCil8Ga0BLGmnC84P9v8UzHfJpZm9slPEZOaaY
    command: npm start

